version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: TransactionalEmail.Api/Dockerfile
    ports:
      - "80:80"
  cli:
    image: cli
    build:
      context: .
      dockerfile: TransactionalEmail.Cli/Dockerfile
    profiles:
      - cli
