# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 5000:5000
  cli:
    image: cli
    build:
      context: .
      dockerfile: Cli/Dockerfile
    ports:
      - 5001:5001
