# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: TransactionalEmail.Api/Dockerfile
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  cli:
    image: cli
    build:
      context: .
      dockerfile: TransactionalEmail.Cli/Dockerfile
    ports:
      - 5011:5011
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  consumer:
    image: consumer
    build:
      context: .
      dockerfile: TransactionalEmail.Consumer/Dockerfile
    ports:
      - 6000:6000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
